name: Check documentation
on: [push, pull_request]
jobs:
  docs:
    name: Build documentation & check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt nox
      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
          nox --version
      - name: Build documentation
        run: nox --force-color --session=docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build
      - name: Check links
        run: nox --force-color --session=linkcheck
